### ISSUE TITLE
json gem version

### ISSUE THREAD

**Issue by mattiaslundback** [algorithmiaio/algorithmia-ruby#19]
Hi. Are having some problems with the JSON gem and algorithmia, version 2.01 (and all others). In Ruby json-gem 2.04 is default, but the requirement here is json 1.8.6. There seems to be a conflict of some sort however:

usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate algorithmia-1.0.1, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)

Is it necessary to require 1.8, or could it be jumped to at least 2.0.2 so this doesn't happen? Don't know how to solve the problem otherwise, it occurs on an Ubuntu machine 14.04 LTS. I know it's a rather old distro, but its the one C9.io runs on and that's what I'm working on.

**Comment by peckjon** [comment]
Thanks @mattiaslundback -- we'll look into changing the requirement or simply switching to >= 1.8, but this'll require some regression testing first

Meanwhile, we'll get back to you ASAP on our support channel regarding a workaround

**Comment by mattiaslundback** [comment]
Thanks. Have been able to solve it temporarily now by downgrading Ruby to 2.3.

It seems to occur on Ruby 2.4 and up.

Mattias Lundbäck
Ekonomismus AB
[ekonomism.us](https://www.ekonomism.us)
Sent from [ProtonMail](https://protonmail.com),
Swiss-based encrypted email.

Sent from ProtonMail mobile

-------- Originalmeddelande --------
På 5 mars 2019 00:04, Jon Peck skrev:

**Comment by peckjon** [comment]
Good to hear!

Basic tests passed, so I'm bumping json to **~> 2.0**

Algorithmia client version 1.1.0 should be available by tomorrow
