### ISSUE TITLE
D.R.Y. for shared DataFile/DataDirectory methods

### ISSUE THREAD

**Issue by anowell** [algorithmiaio/algorithmia-ruby#9]
`sanitize_data_uri` and `parent` could both share implementation in `DataObject` rather than being implemented twice (`DataFile` and `DataDirectory`)

**Comment by lizrush** [comment]
Related #4

**Comment by lizrush** [comment]
Implementation moved to DataObject-- see [this commit](https://github.com/algorithmiaio/algorithmia-ruby/commit/f1fb5f410c09f76787876b05e9e59a11afa4f3b0).
